version: '3.8'

services:
  api:
    build:
      context: ./CargoSimAutomation/API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - mynetwork 
  ui:
    container_name: ui-container
    build:
      context: ./CargoSimAutomation/UI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - mynetwork
networks:
  mynetwork: