version: '3.8'

services:
    app-api:
        build:
            context: ./CargoSimAutomation/API
            dockerfile: Dockerfile
        container_name: app-api
        ports:
        - "8080:8080"
    app-ui:
      image: nginx:alpine
      container_name: app-ui
      ports:
        - "80:80"
      volumes:
        - ./CargoSimAutomation/UI/dist/cargo-sim-automation:/usr/share/nginx/html
      depends_on:
        - app-api